g_Root = getRootElement()


countryNames = {
AD="Andorra",
AE="Arabia",
AF="Afghanistan",
AG="Antigua and Barbuda",
AI="Anguilla",
AL="Albania",
AM="Armenia",
AN="Netherlands Antilles",
AO="Angola",
AP="Asia",
AR="Argentina",
AS="American Samoa",
AT="Austria",
AU="Australia",
AW="Aruba",
AZ="Azerbaijan",
BA="Bosnia and Herzegovina",
BB="Barbados",
BD="Bangladesh",
BE="Belgium",
BF="Burkina Faso",
BG="Bulgaria",
BH="Bahrain",
BI="Burundi",
BJ="Benin",
BM="Bermuda",
BN="Brunei Darussalam",
BO="Bolivia",
BR="Brasil",
BS="Bahamas",
BT="Bhutan",
BW="Botswana",
BY="Belarus",
BZ="Belize",
CA="Canada",
CD="Congo The Democratic",
CF="Central African Republic",
CH="Switzerland",
CI="Ivory Coast ",
CK="Cook Islands",
CL="Chile",
CM="Cameroon",
CN="China",
CO="Colombia",
CR="Costa Rica",
CS="Serbia and Montenegro",
CU="Cuba",
CY="CY",
CZ="Czech Republic",
DE="Germany",
DJ="Djibouti",
DK="Denmark",
DO="Dominican Republic",
DZ="Algeria",
EC="Ecuador",
EE="Estonia",
EG="Egypt",
ER="Eritrea",
ES="Spain",
ET="Ethiopia",
EU="Europa",
FI="Finland",
FJ="Fiji",
FM="Micronesia, Federal States",
FO="Faeroe Islands",
FR="France",
GA="Gabon",
GB="United Kingdom",
GD="Grenada",
GE="Georgia",
GF="French Guiana",
GH="Ghana",
GI="GibraItar",
GL="Greenland",
GM="Gambia",
GR="Greece",
GT="Guatemala",
GU="Guam",
GW="Guinea",
GY="Guyana",
HK="Hong Kong",
HN="Honduras",
HR="Croatia",
HT="Haiti",
HU="Hungary",
ID="Indonesia",
IE="Ireland",
IL="Israel",
IN="India",
IO="India",
IQ="Iraq",
IR="Iran",
IS="Iceland",
IT="Italy",
JM="Jamaica",
JO="Jordan",
JP="Japan",
KE="Kenya",
KG="Kyrgyzstan",
KH="Cambodia",
KI="Kiribati",
KN="Saint Kitts",
KR="Korea",
KW="Kuwait",
KY="Cayman Islands",
KZ="Kazakhstan",
LA="Democratic Republic",
LB="Lebanon",
LC="Santa Lucia",
LI="Liechtenstein",
LK="Sri Lanka",
LR="Liberia",
LS="Lesotho",
LT="LithuaniaI",
LU="Luxembourg",
LV="Latvia",
LY="Libya",
MA="Morocco",
MC="Monaco",
MD="Moldova",
MG="Madagascar",
MK="MK",
ML="Mali",
MM="Myanmar",
MN="Mongolia",
MO="Macau",
MP="MP",
MR="Mauritania",
MT="Malta",
MU="Mauricio",
MV="Maldivas",
MW="Malawi",
MX="Mexico",
MY="Malaysia",
MZ="Mozambique",
NA="NAMIBIA",
NC="New Caledonia",
NE="Nigger",
NF="Norfolk Island",
NG="Nigeria",
NI="Nicaragua",
NL="Netherlands",
NO="Norway",
NP="Nepal",
NR="Nauru",
NU="Niue",
NZ="New Zealand",
OM="Oman",
PA="Panama",
PE="Peru",
PF="French Polynesia",
PG="Papua New Guinea",
PH="Philippines",
PK="Pakistan",
PL="Poland",
PR="Puerto Rico",
PS="Palestinian",
PT="Portugal",
PW="Palau",
PY="Paraguay",
QA="Qatar",
RO="Romania",
RU="Russian",
RS="Serbia",
RW="Rwanda",
SA="Saudi Arabian",
SB="Solomon Islands",
SC="Seychelles",
SD="Sudan",
SE="Sweden",
SG="Singapore",
SI="Slovenia",
SK="Slovak Republic",
SL="Sierra Leone",
SM="San Marino",
SN="Senegal",
SR="Suriname",
SV="El Salvador",
SY="Syrian Arab Republic",
SZ="Swaziland",
TG="Togo",
TH="Thailand",
TJ="Tajikistan",
TM="Turkmenistan",
TN="Tunisia",
TO="Tonga",
TR="Turkey",
TT="Trinidad Tobago",
TV="Tuvalu",
TW="Taiwan Province China",
TZ="Tanzania",
UA="Ukraine",
UG="Uganda",
US="United States",
UY="Uruguay",
UZ="Uzbekistan",
VA="Vatican City",
VE="Venezuela",
VG="Virgin Islands",
VI="Virgin Islands",
VN="Vietnam",
VU="Vanuatu",
WS="Samoa",
YE="Yemen",
YU="Formally Yugoslavia",
ZA="South Africa",
ZM="Zambia",
ZW="Zimbabwe",
ZZ="Reserved"
}


addEventHandler('onPlayerJoin',g_Root,
function ()
    local country = exports['admin']:getPlayerCountry(source)
    setElementData(source,'Country',country)
    outputChatBox('#ffffff' .. getPlayerName(source) .. '#ffffff Entrou no jogo: #FFFFFF[#fff600' .. countryNames[tostring(country)] .. '#FFFFFF] ', getRootElement(), 2, 255, 2, true)
    end
)

addEventHandler('onPlayerChangeNick', g_Root,
    function(oldNick, newNick)
        outputChatBox(' #ffffff' .. oldNick .. '#ffffff Agora é: #fff600' .. newNick, getRootElement(), 3, 180, 255, true)
    end
)
 
addEventHandler('onPlayerQuit', g_Root,
    function(reason)
        outputChatBox('#ffffff' .. getPlayerName(source) .. ' #ffffff Saiu do jogo: #ffffff[#fff600' .. reason .. '#ffffff]', getRootElement(), 255, 0, 0, true)
    end
)